application: Maman14-mac.c parser.c utils.c validator.c operation_dictionary.c first_scan.c
	gcc Maman14-mac.c parser.c utils.c validator.c operation_dictionary.c first_scan.c -Wall -g -ansi -o application -lm

