application: main.c parser.c utils.c validator.c operation_dictionary.c first_scan.c second_scan.c output.c
	gcc main.c parser.c utils.c validator.c operation_dictionary.c first_scan.c second_scan.c output.c -Wall -g -ansi -o application -lm

